/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Period from './Period';





/**
* The Investment model module.
* @module model/Investment
* @version v1
*/
export default class Investment {
    /**
    * Constructs a new <code>Investment</code>.
    * @alias module:model/Investment
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Investment</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Investment} obj Optional instance to populate.
    * @return {module:model/Investment} The populated <code>Investment</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Investment();

            
            
            

            if (data.hasOwnProperty('dateFrom')) {
                obj['dateFrom'] = ApiClient.convertToType(data['dateFrom'], 'Date');
            }
            if (data.hasOwnProperty('dateTo')) {
                obj['dateTo'] = ApiClient.convertToType(data['dateTo'], 'Date');
            }
            if (data.hasOwnProperty('lastPeriod')) {
                obj['lastPeriod'] = Period.constructFromObject(data['lastPeriod']);
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Number');
            }
            if (data.hasOwnProperty('feeSuccess')) {
                obj['feeSuccess'] = ApiClient.convertToType(data['feeSuccess'], 'Number');
            }
            if (data.hasOwnProperty('feeManagement')) {
                obj['feeManagement'] = ApiClient.convertToType(data['feeManagement'], 'Number');
            }
            if (data.hasOwnProperty('feeEntrance')) {
                obj['feeEntrance'] = ApiClient.convertToType(data['feeEntrance'], 'Number');
            }
            if (data.hasOwnProperty('investMinAmount')) {
                obj['investMinAmount'] = ApiClient.convertToType(data['investMinAmount'], 'Number');
            }
            if (data.hasOwnProperty('investMaxAmount')) {
                obj['investMaxAmount'] = ApiClient.convertToType(data['investMaxAmount'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('managerAccountId')) {
                obj['managerAccountId'] = ApiClient.convertToType(data['managerAccountId'], 'String');
            }
            if (data.hasOwnProperty('managerTokensId')) {
                obj['managerTokensId'] = ApiClient.convertToType(data['managerTokensId'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('ordersCount')) {
                obj['ordersCount'] = ApiClient.convertToType(data['ordersCount'], 'Number');
            }
            if (data.hasOwnProperty('totalProfit')) {
                obj['totalProfit'] = ApiClient.convertToType(data['totalProfit'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Date} dateFrom
    */
    dateFrom = undefined;
    /**
    * @member {Date} dateTo
    */
    dateTo = undefined;
    /**
    * @member {module:model/Period} lastPeriod
    */
    lastPeriod = undefined;
    /**
    * @member {Number} period
    */
    period = undefined;
    /**
    * @member {Number} feeSuccess
    */
    feeSuccess = undefined;
    /**
    * @member {Number} feeManagement
    */
    feeManagement = undefined;
    /**
    * @member {Number} feeEntrance
    */
    feeEntrance = undefined;
    /**
    * @member {Number} investMinAmount
    */
    investMinAmount = undefined;
    /**
    * @member {Number} investMaxAmount
    */
    investMaxAmount = undefined;
    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} managerAccountId
    */
    managerAccountId = undefined;
    /**
    * @member {String} managerTokensId
    */
    managerTokensId = undefined;
    /**
    * @member {String} logo
    */
    logo = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    isEnabled = undefined;
    /**
    * @member {Number} rating
    */
    rating = undefined;
    /**
    * @member {Number} ordersCount
    */
    ordersCount = undefined;
    /**
    * @member {Number} totalProfit
    */
    totalProfit = undefined;








}


