/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import InvestmentRequest from './InvestmentRequest';
import InvestmentShort from './InvestmentShort';





/**
* The InvestorProgram model module.
* @module model/InvestorProgram
* @version v1
*/
export default class InvestorProgram {
    /**
    * Constructs a new <code>InvestorProgram</code>.
    * @alias module:model/InvestorProgram
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InvestorProgram</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InvestorProgram} obj Optional instance to populate.
    * @return {module:model/InvestorProgram} The populated <code>InvestorProgram</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvestorProgram();

            
            
            

            if (data.hasOwnProperty('investmentProgram')) {
                obj['investmentProgram'] = InvestmentShort.constructFromObject(data['investmentProgram']);
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], [InvestmentRequest]);
            }
            if (data.hasOwnProperty('totalIn')) {
                obj['totalIn'] = ApiClient.convertToType(data['totalIn'], 'Number');
            }
            if (data.hasOwnProperty('totalOut')) {
                obj['totalOut'] = ApiClient.convertToType(data['totalOut'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/InvestmentShort} investmentProgram
    */
    investmentProgram = undefined;
    /**
    * @member {Array.<module:model/InvestmentRequest>} requests
    */
    requests = undefined;
    /**
    * @member {Number} totalIn
    */
    totalIn = undefined;
    /**
    * @member {Number} totalOut
    */
    totalOut = undefined;








}


