/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The InvestmentShort model module.
* @module model/InvestmentShort
* @version v1
*/
export default class InvestmentShort {
    /**
    * Constructs a new <code>InvestmentShort</code>.
    * @alias module:model/InvestmentShort
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InvestmentShort</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InvestmentShort} obj Optional instance to populate.
    * @return {module:model/InvestmentShort} The populated <code>InvestmentShort</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvestmentShort();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('managerAccountId')) {
                obj['managerAccountId'] = ApiClient.convertToType(data['managerAccountId'], 'String');
            }
            if (data.hasOwnProperty('managerTokensId')) {
                obj['managerTokensId'] = ApiClient.convertToType(data['managerTokensId'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('ordersCount')) {
                obj['ordersCount'] = ApiClient.convertToType(data['ordersCount'], 'Number');
            }
            if (data.hasOwnProperty('totalProfit')) {
                obj['totalProfit'] = ApiClient.convertToType(data['totalProfit'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} managerAccountId
    */
    managerAccountId = undefined;
    /**
    * @member {String} managerTokensId
    */
    managerTokensId = undefined;
    /**
    * @member {String} logo
    */
    logo = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    isEnabled = undefined;
    /**
    * @member {Number} rating
    */
    rating = undefined;
    /**
    * @member {Number} ordersCount
    */
    ordersCount = undefined;
    /**
    * @member {Number} totalProfit
    */
    totalProfit = undefined;








}


