/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The InvestmentsFilter model module.
* @module model/InvestmentsFilter
* @version v1
*/
export default class InvestmentsFilter {
    /**
    * Constructs a new <code>InvestmentsFilter</code>.
    * @alias module:model/InvestmentsFilter
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InvestmentsFilter</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InvestmentsFilter} obj Optional instance to populate.
    * @return {module:model/InvestmentsFilter} The populated <code>InvestmentsFilter</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvestmentsFilter();

            
            
            

            if (data.hasOwnProperty('managerId')) {
                obj['managerId'] = ApiClient.convertToType(data['managerId'], 'String');
            }
            if (data.hasOwnProperty('brokerId')) {
                obj['brokerId'] = ApiClient.convertToType(data['brokerId'], 'String');
            }
            if (data.hasOwnProperty('brokerTradeServerId')) {
                obj['brokerTradeServerId'] = ApiClient.convertToType(data['brokerTradeServerId'], 'String');
            }
            if (data.hasOwnProperty('investMaxAmountFrom')) {
                obj['investMaxAmountFrom'] = ApiClient.convertToType(data['investMaxAmountFrom'], 'Number');
            }
            if (data.hasOwnProperty('investMaxAmountTo')) {
                obj['investMaxAmountTo'] = ApiClient.convertToType(data['investMaxAmountTo'], 'Number');
            }
            if (data.hasOwnProperty('sorting')) {
                obj['sorting'] = ApiClient.convertToType(data['sorting'], 'String');
            }
            if (data.hasOwnProperty('skip')) {
                obj['skip'] = ApiClient.convertToType(data['skip'], 'Number');
            }
            if (data.hasOwnProperty('take')) {
                obj['take'] = ApiClient.convertToType(data['take'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} managerId
    */
    managerId = undefined;
    /**
    * @member {String} brokerId
    */
    brokerId = undefined;
    /**
    * @member {String} brokerTradeServerId
    */
    brokerTradeServerId = undefined;
    /**
    * @member {Number} investMaxAmountFrom
    */
    investMaxAmountFrom = undefined;
    /**
    * @member {Number} investMaxAmountTo
    */
    investMaxAmountTo = undefined;
    /**
    * @member {module:model/InvestmentsFilter.SortingEnum} sorting
    */
    sorting = undefined;
    /**
    * @member {Number} skip
    */
    skip = undefined;
    /**
    * @member {Number} take
    */
    take = undefined;






    /**
    * Allowed values for the <code>sorting</code> property.
    * @enum {String}
    * @readonly
    */
    static SortingEnum = {
    
        /**
         * value: "ByRatingAsc"
         * @const
         */
        "ByRatingAsc": "ByRatingAsc",
    
        /**
         * value: "ByRatingDesc"
         * @const
         */
        "ByRatingDesc": "ByRatingDesc",
    
        /**
         * value: "ByProfitAsc"
         * @const
         */
        "ByProfitAsc": "ByProfitAsc",
    
        /**
         * value: "ByProfitDesc"
         * @const
         */
        "ByProfitDesc": "ByProfitDesc",
    
        /**
         * value: "ByOrdersAsc"
         * @const
         */
        "ByOrdersAsc": "ByOrdersAsc",
    
        /**
         * value: "ByOrdersDesc"
         * @const
         */
        "ByOrdersDesc": "ByOrdersDesc"    
    };



}


