/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import InvestorProgram from './InvestorProgram';





/**
* The InvestorDashboard model module.
* @module model/InvestorDashboard
* @version v1
*/
export default class InvestorDashboard {
    /**
    * Constructs a new <code>InvestorDashboard</code>.
    * @alias module:model/InvestorDashboard
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InvestorDashboard</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InvestorDashboard} obj Optional instance to populate.
    * @return {module:model/InvestorDashboard} The populated <code>InvestorDashboard</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvestorDashboard();

            
            
            

            if (data.hasOwnProperty('programs')) {
                obj['programs'] = ApiClient.convertToType(data['programs'], [InvestorProgram]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/InvestorProgram>} programs
    */
    programs = undefined;








}


