/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import BrokerTradeServer from './BrokerTradeServer';





/**
* The ManagerAccount model module.
* @module model/ManagerAccount
* @version v1
*/
export default class ManagerAccount {
    /**
    * Constructs a new <code>ManagerAccount</code>.
    * @alias module:model/ManagerAccount
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ManagerAccount</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ManagerAccount} obj Optional instance to populate.
    * @return {module:model/ManagerAccount} The populated <code>ManagerAccount</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManagerAccount();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('ipfsHash')) {
                obj['ipfsHash'] = ApiClient.convertToType(data['ipfsHash'], 'String');
            }
            if (data.hasOwnProperty('isConfirmed')) {
                obj['isConfirmed'] = ApiClient.convertToType(data['isConfirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('registrationDate')) {
                obj['registrationDate'] = ApiClient.convertToType(data['registrationDate'], 'Date');
            }
            if (data.hasOwnProperty('brokerTradeServer')) {
                obj['brokerTradeServer'] = BrokerTradeServer.constructFromObject(data['brokerTradeServer']);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} login
    */
    login = undefined;
    /**
    * @member {String} currency
    */
    currency = undefined;
    /**
    * @member {String} ipfsHash
    */
    ipfsHash = undefined;
    /**
    * @member {Boolean} isConfirmed
    */
    isConfirmed = undefined;
    /**
    * @member {Date} registrationDate
    */
    registrationDate = undefined;
    /**
    * @member {module:model/BrokerTradeServer} brokerTradeServer
    */
    brokerTradeServer = undefined;








}


