/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The NewInvestmentRequest model module.
* @module model/NewInvestmentRequest
* @version v1
*/
export default class NewInvestmentRequest {
    /**
    * Constructs a new <code>NewInvestmentRequest</code>.
    * @alias module:model/NewInvestmentRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>NewInvestmentRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NewInvestmentRequest} obj Optional instance to populate.
    * @return {module:model/NewInvestmentRequest} The populated <code>NewInvestmentRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewInvestmentRequest();

            
            
            

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('brokerTradeServerId')) {
                obj['brokerTradeServerId'] = ApiClient.convertToType(data['brokerTradeServerId'], 'String');
            }
            if (data.hasOwnProperty('tradePlatformPassword')) {
                obj['tradePlatformPassword'] = ApiClient.convertToType(data['tradePlatformPassword'], 'String');
            }
            if (data.hasOwnProperty('depositAmount')) {
                obj['depositAmount'] = ApiClient.convertToType(data['depositAmount'], 'Number');
            }
            if (data.hasOwnProperty('tokenName')) {
                obj['tokenName'] = ApiClient.convertToType(data['tokenName'], 'String');
            }
            if (data.hasOwnProperty('tokenSymbol')) {
                obj['tokenSymbol'] = ApiClient.convertToType(data['tokenSymbol'], 'String');
            }
            if (data.hasOwnProperty('dateFrom')) {
                obj['dateFrom'] = ApiClient.convertToType(data['dateFrom'], 'Date');
            }
            if (data.hasOwnProperty('dateTo')) {
                obj['dateTo'] = ApiClient.convertToType(data['dateTo'], 'Date');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('feeEntrance')) {
                obj['feeEntrance'] = ApiClient.convertToType(data['feeEntrance'], 'Number');
            }
            if (data.hasOwnProperty('feeManagement')) {
                obj['feeManagement'] = ApiClient.convertToType(data['feeManagement'], 'Number');
            }
            if (data.hasOwnProperty('feeSuccess')) {
                obj['feeSuccess'] = ApiClient.convertToType(data['feeSuccess'], 'Number');
            }
            if (data.hasOwnProperty('investMinAmount')) {
                obj['investMinAmount'] = ApiClient.convertToType(data['investMinAmount'], 'Number');
            }
            if (data.hasOwnProperty('investMaxAmount')) {
                obj['investMaxAmount'] = ApiClient.convertToType(data['investMaxAmount'], 'Number');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} userId
    */
    userId = undefined;
    /**
    * @member {String} brokerTradeServerId
    */
    brokerTradeServerId = undefined;
    /**
    * @member {String} tradePlatformPassword
    */
    tradePlatformPassword = undefined;
    /**
    * @member {Number} depositAmount
    */
    depositAmount = undefined;
    /**
    * @member {String} tokenName
    */
    tokenName = undefined;
    /**
    * @member {String} tokenSymbol
    */
    tokenSymbol = undefined;
    /**
    * @member {Date} dateFrom
    */
    dateFrom = undefined;
    /**
    * @member {Date} dateTo
    */
    dateTo = undefined;
    /**
    * @member {String} logo
    */
    logo = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Number} feeEntrance
    */
    feeEntrance = undefined;
    /**
    * @member {Number} feeManagement
    */
    feeManagement = undefined;
    /**
    * @member {Number} feeSuccess
    */
    feeSuccess = undefined;
    /**
    * @member {Number} investMinAmount
    */
    investMinAmount = undefined;
    /**
    * @member {Number} investMaxAmount
    */
    investMaxAmount = undefined;
    /**
    * @member {Number} period
    */
    period = undefined;








}


