/**
 * Core API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The WalletTransaction model module.
* @module model/WalletTransaction
* @version v1
*/
export default class WalletTransaction {
    /**
    * Constructs a new <code>WalletTransaction</code>.
    * @alias module:model/WalletTransaction
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>WalletTransaction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WalletTransaction} obj Optional instance to populate.
    * @return {module:model/WalletTransaction} The populated <code>WalletTransaction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WalletTransaction();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {module:model/WalletTransaction.TypeEnum} type
    */
    type = undefined;
    /**
    * @member {Number} amount
    */
    amount = undefined;
    /**
    * @member {Date} date
    */
    date = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "Deposit"
         * @const
         */
        "Deposit": "Deposit",
    
        /**
         * value: "Withdraw"
         * @const
         */
        "Withdraw": "Withdraw",
    
        /**
         * value: "OpenProgram"
         * @const
         */
        "OpenProgram": "OpenProgram",
    
        /**
         * value: "InvestToProgram"
         * @const
         */
        "InvestToProgram": "InvestToProgram",
    
        /**
         * value: "WithdrawFromProgram"
         * @const
         */
        "WithdrawFromProgram": "WithdrawFromProgram"    
    };



}


